api/urls.py
from django.conf.urls import  url
from rest_framework.routers import DefaultRouter
from api.viewsets import LabViewSet, UserViewSet, GroupViewSet, PrincipalViewSet
from django_logger.api.views import LogViewset

router = DefaultRouter()
router.register(r'labs', LabViewSet, 'Lab')
router.register(r'users', UserViewSet, 'User')
router.register(r'unix_groups', GroupViewSet, 'UnixGroup')
router.register(r'principals', PrincipalViewSet, 'Principal')
router.register(r'logs', LogViewset, 'Log')


urlpatterns = router.urls

# urlpatterns = [
#     url(r'^', 'ezreg.payment.touchnet.views.postback',name='touchnet_postback'),
# ]

gcportal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from gcportal import views
from api import urls as api_urls
from registration.views import ResetPasswordView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index,name='index'),
    url(r'^home/$', views.home,name='home'),
    url(r'^software/$', views.software,name='software'),
    url(r'^machines/register/$', views.register_machine,name='register_machine'),
    url(r'^machines/$', views.machines,name='machines'),
    url(r'^machines/(?P<pk>\d+)/admin/$', views.admin_machine,name='admin_machine'),
    url(r'^machines/(?P<pk>\d+)/confirm/$', views.confirm_machine,name='confirm_machine'),
    url(r'^machines/(?P<pk>\d+)/retire/$', views.retire_machine,name='retire_machine'),
    url(r'^machines/(?P<pk>\d+)/delete/$', views.delete_machine,name='delete_machine'),
    url(r'^policies/$', views.policies,name='policies'),
    url(r'^profile/$', views.profile,name='profile'),
    url(r'^policies/(?P<pk>\d+)/$', views.policy,name='policy'),
    url(r'^request_forms/$', views.request_forms,name='request_forms'),
    url(r'^process_form/(?P<form_id>\w+)/$', views.process_form,name='process_form'),
    url(r'^labs/manage/$', views.manage_labs,name='manage_labs'),
    url(r'^labs/manage_groups/$', views.manage_unix_groups,name='manage_unix_groups'),
    url(r'^labs/create/$', views.create_lab,name='create_lab'),
    url(r'^users/manage/$', views.manage_users,name='manage_users'),
    url(r'^users/manage/(?P<username>\w+)/$', views.user_details,name='user_details'),
    url(r'^users/manage/(?P<username>\w+)/modify_principal/$', views.modify_principal,name='modify_principal'),
    url(r'^registration/', include('registration.urls')),
    url(r'^api/', include(api_urls)),
    url(r'^accounts/login/$', auth_views.login, name="login",kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/logout/$', auth_views.logout, name="logout"),
    url(r'^password_reset/(?P<token>[^/]+)/', ResetPasswordView.as_view(), name='password_reset'),
    url(r'^sponsorship/request_sponsor/$', views.request_new_sponsor,name='request_sponsor'),
    url(r'^sponsorship/confirm/(?P<token>[^/]+)/', views.ConfirmSponsor.as_view(), name='confirm_sponsor'),
    url(r'^account/request_password_reset/$', views.request_new_password,name='request_new_password'),
    url(r'^account/password_reset/confirm/(?P<token>[^/]+)/', views.ConfirmPasswordReset.as_view(), name='confirm_password_reset'),
    
    
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gcportal/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core import validators
from django.core.mail import send_mail
from django.db import models
from django.template.context import Context
from django.template.loader import get_template
from gcportal.emails import Mailer
import subprocess
import datetime
from django_confirm.models import Token
from django.urls.base import reverse
from kerberos.admin import KerberosAdmin, Principal
from signals import revoke_sponsor, set_sponsor
from django_logger.models import Log

class Lab(models.Model):
    first_name = models.CharField(max_length=30,null=True,blank=True,db_index=True)
    last_name = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True,null=True)
#     owner = models.ForeignKey(User)
    @property
    def name(self):
        return '%s, %s'%(self.last_name,self.first_name) if self.first_name else self.last_name
    def has_permission(self,user,permission,use_superuser=True):
        if permission == Log.PERMISSION_VIEW:
            permission = LabPermission.PERMISSION_ADMIN
        return (use_superuser and user.is_superuser) or LabPermission.objects.filter(lab=self,user=user,permission=permission).first() is not None 
    def __unicode__(self):
        return self.name

# class Lab(models.Model):
#     first_name = models.CharField(max_length=30,null=True,blank=True,db_index=True)
#     last_name = models.CharField(max_length=30,db_index=True)
#     affiliation = models.CharField(max_length=50,choices=((affiliation,affiliation) for affiliation in settings.LAB_AFFILIATIONS),null=True,blank=True,db_index=True)
#     description = models.TextField(db_index=True)
#     url = models.URLField(blank=True,null=True)
#     slug = models.SlugField(max_length=50,unique=True,null=True)
#     @property
#     def name(self):
#         return '%s, %s'%(self.last_name,self.first_name) if self.first_name else self.last_name
#     def get_directory_name(self):
#         return call_directory_function('get_lab_directory_name',self)
# #         parts = [self.last_name,self.first_name] if self.first_name else [self.last_name]
# #         return make_directory_name('_'.join(parts))
#     def get_group_directory(self,group,full=True):
#         return call_directory_function('get_group_lab_directory',self,group,full=full)
# #         path = os.path.join(make_directory_name(group.name),'labs',self.get_directory_name())#self.slug
# #         if full:
# #             path = safe_join(FILES_ROOT,path)
# #         return path
#     def __unicode__(self):
#         return self.name

class LabPermission(models.Model):
#     PERMISSION_MEMBER = 'member'
    PERMISSION_APPROVER = 'approver'
    PERMISSION_ADMIN = 'admin'
    GROUP_PERMISSIONS = ((PERMISSION_APPROVER,"Can approve group members"),(PERMISSION_ADMIN,"Can administer group"))#(PERMISSION_MEMBER,"Group member"),
    user = models.ForeignKey(User,related_name='lab_permissions')
    lab = models.ForeignKey(Lab,related_name='lab_permissions')
    permission = models.CharField(choices=GROUP_PERMISSIONS,max_length=15)
    @staticmethod
    def get_labs_with_permissions(user,permissions,qs=None,require_all=True,use_superuser=True):
        qs = qs if qs else Lab.objects.all()
        if use_superuser and user.is_superuser:
            return qs
        qs = qs.filter(lab_permissions__user=user)
        if not require_all:
            return qs.filter(lab_permissions__permission__in=permissions)
        for p in permissions:
            qs = qs.filter(lab_permissions__permission=p)
        return qs
    @staticmethod
    def has_permission(lab_id,user,permission,use_superuser=True):
        return (use_superuser and user.is_superuser) or LabPermission.objects.filter(lab_id=lab_id,user=user,permission=permission).first() is not None 
    class Meta:
        unique_together = ('user','lab','permission')

class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name="profile")
    sponsor = models.ForeignKey(Lab, null=True, blank=True,on_delete=models.SET_NULL,help_text='Enter group or lab sponsoring the account.  If your group is not listed, please email "sysadmin@genomecenter.ucdavis.edu".',related_name='user_profiles')
    category = models.CharField(max_length=15, null=True, blank=True, choices=(('undergrad','Undergraduate Student'),('grad','Graduate Student'),('postdoc','Post Doctorate'),('staff','Staff'),('faculty','Faculty'),('other','Other')))
    ucd = models.BooleanField('UCD',default=False,help_text="Are you a UC Davis student or employee?")
    uid = models.PositiveIntegerField(unique=True,null=True,blank=True)
    def __unicode__(self):
        return str(self.user)
    def revoke_sponsor(self,revoked_by):
        Mailer().send_mail('Genome Center account sponsorship revoked', to=[self.user.email],bcc=[settings.SYSADMIN_TO_EMAIL], context={'revoked_by':revoked_by, 'user':self.user}, message_template='portal/emails/sponsorship_revoked.txt')
        sponsor = self.sponsor
        self.sponsor = None
        self.save()
        revoke_sponsor.send(sender=self.__class__,user=self.user,sponsor=sponsor)
#         self.expire_principal()
    def set_sponsor(self,lab):
        self.sponsor = lab
        self.save()
        set_sponsor.send(sender=self.__class__,user=self.user,sponsor=lab)
#         self.enable_principal()
    def get_expiration_date(self):
        if self.category in ['staff','faculty']:
            return None
        return datetime.datetime.now() + datetime.timedelta(5*365) #expires in 5 years for all others
#     def get_principal(self):
#         if not getattr(settings,'KRB_ENABLE',False):
#             return None
#         kadm = KerberosAdmin.create()
#         return kadm.get_principal(self.user)
#     def expire_principal(self):
#         if getattr(settings,'KRB_ENABLE',False):
#             kadm = KerberosAdmin.create()
#             kadm.set_expiration(self.user)
#     def enable_principal(self):
#         if getattr(settings,'KRB_ENABLE',False):
#             kadm = KerberosAdmin.create()
#             kadm.set_expiration(self.user,date=self.get_expiration_date())
    @staticmethod
    def generate_uid():
        profile = UserProfile.objects.filter(uid__isnull=False).order_by('-uid').first()
        print profile
        print profile.uid
        uid = profile.uid
        while True:
            uid += 1
            if subprocess.call(['getent','passwd',str(uid)]) == 2:
                return uid
    def create_email_change_token(self,email):
        expires = datetime.datetime.now() + datetime.timedelta(days=1)
        Token.objects.filter(action='change_email',object_id=self.user_id).delete()
        return Token.create(action='change_email',content_object=self.user,data={'email':email},expires=expires)
    def send_email_change(self,email):
        token = self.create_email_change_token(email)
        url = settings.BASE_URL+reverse('confirm_change_email', kwargs={'token':token.token})
        emails = [token.data['email']]
        Mailer().send_mail('Confirm email address change', to=emails, context={'url':url,'user':self.user}, message_template='portal/emails/change_email_body.txt')
    def create_password_reset_token(self):
        expires = datetime.datetime.now() + datetime.timedelta(days=1)
        Token.objects.filter(action='password_reset',object_id=self.user_id).delete()
        return Token.create(action='password_reset',content_object=self.user,expires=expires)
    def send_password_reset(self):
        token = self.create_password_reset_token()
        url = settings.BASE_URL+reverse('password_reset', kwargs={'token':token.token})
        Mailer().send_mail('Reset your Genome Center password', to=[self.user.email], context={'user':self.user,'url':url}, message_template='portal/emails/password_reset.txt')

def user_unicode(self):
    return "%s %s" % (self.first_name, self.last_name) if self.first_name and self.last_name else self.username
User.__unicode__ = user_unicode

def principal(self):
    if getattr(settings,'KRB_ENABLE',False):
        if not hasattr(self, '_principal'):
#             kadm = KerberosAdmin.create()
            self._principal = Principal(self.username)
        return self._principal
    else:
        return None
User.principal = property(principal)

def has_permission(self,user,permission):
    return user == self or user.is_superuser


class Policy(models.Model):
#     TYPE_NETWORK = 'network'
#     TYPE_OTHER = 'other'
#     type = models.CharField(max_length=15,choices=((TYPE_NETWORK,'Network use policy'),(TYPE_OTHER,'Other')))
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    text = models.TextField()
    required = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "policies"

class AcceptedPolicy(models.Model):
    policy = models.ForeignKey(Policy,related_name='accepted_policies')
    user = models.ForeignKey(User,related_name='accepted_policies')
    text = models.TextField()
    accepted = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = ('policy','user')

# Probably going to use captive portal software for mac registration
class Machine(models.Model):
    TYPE_LAPTOP = 'laptop'
    TYPE_DESKTOP = 'desktop'
    TYPE_TABLET = 'tablet'
    TYPE_PHONE = 'phone'
    TYPE_SERVER = 'server'
    TYPE_OTHER = 'other'
    TYPES = ((TYPE_DESKTOP,'Desktop'),(TYPE_LAPTOP,'Laptop'),(TYPE_PHONE,'Phone'),(TYPE_TABLET,'Tablet'),(TYPE_SERVER,'Server'),(TYPE_OTHER,'Other'))
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    type = models.CharField(max_length=10,choices=TYPES)
#     operating_system = models.CharField()
    mac_address = models.CharField(max_length=20,
        validators=[

gcportal/forms.py
from django import forms
from gcportal.models import Machine , Lab
from django.contrib.auth.models import User
from django.conf import settings
from kerberos.admin import KerberosAdmin



class MachineForm(forms.ModelForm):
    class Meta:
        model = Machine
        fields = ('type','description','mac_address','mac_address_2','mac_address_3','mac_address_4')

class PolicyForm(forms.Form):
    accept = forms.BooleanField(initial=False,required=True,error_messages={'required': "Acceptance of this policy is required",})

class RequestSponsorForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    lab = forms.ModelChoiceField(queryset=Lab.objects.all())
    def clean(self):
        cleaned_data = super(RequestSponsorForm, self).clean()
        email = cleaned_data.get('email')
        username = cleaned_data.get('username')
        user = User.objects.filter(email=email,username=username,profile__sponsor__isnull=True).first()
        if not user:
            raise forms.ValidationError("That email/username combination does not match any user requiring a sponsor")

class RequestPasswordForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    def clean(self):
        cleaned_data = super(RequestPasswordForm, self).clean()
        email = cleaned_data.get('email')
        username = cleaned_data.get('username')
        user = User.objects.filter(email=email,username=username,profile__sponsor__isnull=False).first()
        if not user:
            raise forms.ValidationError("That email/username combination couldn't be found")

class LabForm(forms.ModelForm):
    class Meta:
        model = Lab
        exclude = ()
        labels = {'last_name':'Last name / Company'}
#     def clean_email(self):


class LabPIForm(LabForm):
    user = None
    principal_exists = False
    email = forms.EmailField(label='PI Email',required=False,help_text="Optionally enter the email address of the PI for the group to assign them admin privileges.")
    username = forms.CharField(label='PI Username/Principal',required=False,help_text="If the PI already has a kerberos account, enter the principal.")
#     create = forms.BooleanField(label='Create account',default=False,help_text="Create the account if it doesn't yet exist.")
#     def clean_email(self):
    def clean(self):
        cleaned_data = super(LabPIForm, self).clean()
        email = cleaned_data.get('email')
        username = cleaned_data.get('username')
#         create = cleaned_data.get('create')
        if username:
            if not email:
                raise forms.ValidationError("You must provide an email when assigning/creating a PI for a lab")
            self.user = User.objects.filter(username=username).first()
            if self.user and self.user.email != email:
                raise forms.ValidationError("That email/username combination does not match any user")
            elif not self.user:
                if getattr(settings, 'KRB_ENABLE',False):
                    kadm = KerberosAdmin.create()
                    if not kadm.username_exists(username):
                        raise forms.ValidationError("That kerberos principal does not exist")
                    else:
                        self.principal_exists = True
                else:
                    raise forms.ValidationError("No user with that username exist")
                    
        else:
            self.user = User.objects.filter(email=email).first()
        
class PrincipalForm(forms.Form):
    name = 'Modify Principal'
    expire = forms.DateTimeField(label="Account expiration date",required=False)
    pwexpire = forms.DateTimeField(label="Password expiration date",required=False)
    policy = forms.CharField(label="Password policy",required=False)
    def __init__(self,*args,**kwargs):
        self.principal = kwargs.pop('principal')
        if len(args) == 0 and not kwargs.get('data',None):
            kwargs['initial'] = self.principal.serialize()#{name:getattr(self.principal, name, None) for name, field in self.fields.iteritems()}#{'expire':self.principal.expire,'pwexpires':self.principal.pwexpires,'policy':self.policy}
        super(PrincipalForm, self).__init__(*args,**kwargs)
    def save(self):
        if self.is_valid():
            for key,val in self.cleaned_data.iteritems():
                setattr(self.principal.princ, key, val or None)
            self.principal.princ.commit()
            
                

gcportal/templates/portal/approve_password_reset.html
{% extends 'base.html' %}
{% block content %}
{% if approved %}
<h2>"{{user}}" has been emailed a password reset token.</h2>
{% else %}
<h2>Password reset request for user "{{user}}" denied.</h2>
{% endif %}
{% endblock %}

gcportal/templates/portal/change_sponsor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h2>Request new sponsor</h2>
{% if lab %}
	<h3>Your sponsorship request has been sent to "{{lab}}".  You will be notified if your sponsorship request is approved.</h3>
{% else %}
	<form method="POST" action=".">
	{% csrf_token %}
	{{form|crispy}}
	<button class="btn btn-default">Submit</button>
	</form>

{% endif %}
{% endblock %}

gcportal/templates/portal/home.html
{% extends 'base.html' %}
{% block content %}

{% if request.user.first_name %}
<h2>Welcome to the Bioinformatics Core Portal, {{request.user.first_name}}!</h2>
{% endif %}
{% if not request.user.email or not request.user.first_name or not request.user.last_name %}
<h3><span class="glyphicon glyphicon-warning-sign error"></span> It seems you have an incomplete profile.  Please take a minute to <a href="{% url 'profile' %}">complete your profile</a> so that we can contact you when needed.</h3>
{% endif %}
{% if policies %}
<h3><span class="glyphicon glyphicon-warning-sign error"></span> There are policies that require your attention.  Please <a href="{% url 'policies' %}">visit the policies page</a> to review and accept the required policies.</h3>
{% endif %}
{% if registrations %}
<h3><span class="glyphicon glyphicon-warning-sign error"></span> There {% if registrations.count == 1 %}is an account request{% else %}are {{registrations.count}} account requests{% endif %} for your lab pending approval.  Please <a href="{% url 'pending_registrations' %}">approve or deny</a> the pending account request{% if registrations.count > 1 %}s{%endif%}.</h3>
{% endif %}
{% endblock %}

gcportal/templates/portal/index.html
{% extends 'base.html' %}
{% block content %}
<p>
Welcome to the UC Davis Genome Center portal.  Here you can manage some of your Genome Center compute resources.  Using the portal you can:
<ul>
<li>Register mac addresses for network access.</li>
<li>Approve requests for an account to be added to your lab.</li>
<li>Review and accept policies for accessing the Genome Center network and servers.</li>
<li>View a list of software packages available on the Genome Center compute clusters.</li>
<li>Request a new account.</li>
</ul>  
</p>
 
<p>
If you are joining the Genome Center or have recently become part of one of the associated groups, you probably want to
<a href="{% url 'register'%}">request an account.</a>
</p>
<p>
Forgotten your password? <a href="{% url 'request_new_password'%}">Request a new password.</a>
</p>
<p>
If you've lost your sponsor and your account has been locked, you may <a href="{% url 'request_sponsor'%}">request a new sponsor.</a>
</p>
<p>
If you have no idea where you are, or how you got here, you may be lost.
</p>
{% endblock %}

gcportal/templates/portal/machines.html
{% extends 'base.html' %}
{% block content %}

{% if message %}
<div class="alert alert-success" role="alert">{{message}}</div>
{%endif%}

<h2>Network Registration</h2>
<p><a href="{% url 'register_machine' %}">Register</a> a new mac address.</p>
{% if not machines %}
<p>You do not have any registered machines.</p>
{% else %}
<table class="table">
<tr><th>Created</th><th>Type</th><th>Mac</th><th>Description</th><th>Removed</th><th>Action</th></tr>
{% for m in machines %}
<tr>
	<td>{{m.created}}</td>
	<td>{{m.get_type_display}}</td>
	<td>
		{{m.mac_address}}
		{%if m.mac_address_2%}<br>{{m.mac_address_2}}{%endif%}
		{%if m.mac_address_3%}<br>{{m.mac_address_3}}{%endif%}
		{%if m.mac_address_4%}<br>{{m.mac_address_4}}{%endif%}
	</td>
	<td>{{m.description}}</td>
	<td>{% if m.retired %}{{m.retired}}{% else %}N/A{% endif %}</td>
	<td>
	{% if m.entered %}
		{% if not m.retired %}
		<a onClick="return confirm('Are you sure you want to retire this machine from the network?')" class="btn btn-sm btn-warning" href="{% url 'retire_machine' pk=m.pk %}">Retire</a>	
		{% endif %}
	{% else %}
	<a onClick="return confirm('Are you sure you want to delete this machine?')" class="btn btn-sm btn-danger" href="{% url 'delete_machine' pk=m.pk %}">Delete</a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</table>
{% endif %}
{% endblock %}

gcportal/templates/portal/manage_labs.html
{% extends 'base.html' %}
{% block 'headend' %}
<script>
angular.module('app')
.controller('LabController', ['$scope','$http','growl','Lab','User','DRFNgTableParams',LabController])

function LabController($scope,$http,growl,Lab,User,DRFNgTableParams) {
	$scope.labs = Lab.query({has_permissions:['admin']}).$promise.then(function(labs){
		$scope.labs = labs;
		if (labs.length == 1){
			$scope.selected_lab = labs[0];
			$scope.modifyLab();
		}
			
	});
	$scope.modifyLab = function(){
		console.log($scope.selected_lab);
		$scope.lab = new Lab($scope.selected_lab);
		$scope.lab.$get_permissions();
		$scope.sponsoring = User.query({profile__sponsor__id:$scope.lab.id});
	};
	$scope.revokeSponsorship = function(user,lab){
		if (!confirm("Are you sure you want to revoke sponsorship by the lab" +lab.name+" for the user "+user.first_name+" "+user.last_name+"? Their account may be locked."))
			return;
		user.$revoke_sponsorship({lab_id:lab.id},function(){
			$scope.sponsoring.splice($scope.sponsoring.indexOf(user),1);
			growl.success('Sponsorship revoked',{ttl: 5000});
		});
	};
	$scope.init = function(kwargs){
		$scope.permissions = kwargs.permissions;
		$scope.content_type = kwargs.content_type;
	};
	$scope.savePermissions = function(){
		$scope.disable_button = true;
		$scope.lab.$set_permissions(
			function(){
				$scope.disable_button = false;
				growl.success("User permissions have been updated",{ttl: 5000});
			},
			function(){
				$scope.disable_button = false;
				growl.error("User permissions update has failed",{ttl: 5000});
			}
		);
	};
	$scope.getUsers = function(search){
		return User.query({search:search}).$promise;
	}
	$scope.addUser = function($item,$model,permission){
		for (var i in $scope.lab.permissions[permission]){
			if ($scope.lab.permissions[permission][i].id == $item.id){
				growl.warning("User already has this permission",{ttl: 5000});
				return;
			}
		}
		Lab.add_permission({permission:permission,user_id:$item.id,id:$scope.lab.id},function(){
			$scope.lab.permissions[permission].push($item);	
			growl.success("User permission added.",{ttl: 5000});
		},function(){
			growl.error("Error adding user permission.",{ttl: 5000});
		})
	}
	$scope.removePermission = function(user,permission,index){
		Lab.remove_permission({permission:permission,user_id:user.id,id:$scope.lab.id},function(){
			$scope.lab.permissions[permission].splice(index,1);
			growl.success("User permission removed.",{ttl: 5000});
		},function(){
			growl.error("Error removing user permission.",{ttl: 5000});
		})
	}
}

</script>
{% endblock %}

{% block content %}
<div ng-controller="LabController" ng-init='init({ permissions: {{permissions|safe}}, content_type:{{content_type.id}} })'>
	<div class="row" ng-show="labs.length > 1">
	<div class="col-md-2"><label>Select lab:</label></div>
	<div class="col-md-4"> 
		<select ng-model="selected_lab" ng-change="modifyLab()" ng-options="lab as lab.name for lab in labs track by lab.id" class="form-control"></select>
	 </div>
	 </div>
	<div ng-if="lab">
	<h2>{[lab.name]}</h2>
	<div ng-show="sponsoring.length">
			<h3>Sponsored users</h3>
			<table class="table m-t-3" style="margin-top:20px;">
				<tr><th>User</th><th>Email</th><th>Username</th><th></th></tr>
				<tr ng-repeat="u in sponsoring">
					<td>{[u.first_name]} {[u.last_name]}</td>
					<td>{[u.email]}</td>
					<td>{[u.username]}</td>
					<td><button class="btn btn-danger btn-xs" title="Revoke the user's account sponsorship for this lab" ng-click="revokeSponsorship(u,lab)">Revoke</button></td>
				</tr>
			</table>
	</div>
	<h3 ng-show="!sponsoring.length">This lab is not currently sponsoring any user accounts.</h3>
	<h2>User permissions</h2>
	    <div ng-repeat="(permission, users) in lab.permissions">
	    	<h2>{[permission | uppercase]}: {[permissions[permission]]}</h2>
	    	<div class="row">
				<div class="col-md-2"><label>Add a user:</label></div>
				<div class="col-md-4">
				    <input type="text" ng-model="newUser" placeholder="Search users"  
				    	uib-typeahead="user as user.first_name + ' ' + user.last_name + ', '+user.email+', '+user.username for user in getUsers($viewValue)" 
				    	typeahead-loading="loadingUsers" typeahead-no-results="noResults" class="form-control" typeahead-on-select="addUser($item,$model,permission);newUser = '';">
				    <i ng-show="loadingUsers" class="glyphicon glyphicon-refresh"></i>
				    <div ng-show="noResults">
				      <i class="glyphicon glyphicon-remove"></i> No Results Found
				    </div>
			    </div>
		    </div>
	    	<div ng-if="users.length > 0">
			<table class="table m-t-3" style="margin-top:20px;">
			<tr><th>User</th><th>Email</th><th>Username</th><th></th></tr>
			<tr ng-repeat="user in users">
				<td>{[user.first_name]} {[user.last_name]}</td>
				<td>{[user.email]}</td>
				<td>{[user.username]}</td>
				<td><button ng-click="removePermission(user,permission,$index)" class="btn btn-danger btn-xs">Remove</button></td>
			</tr>
			</table>
			<!-- <button ng-click="savePermissions()" class="btn btn-primary"  ng-disabled="disable_button">Save</button> -->
			</div>
			<h3 ng-hide="users.length">There are no users with this permission</h3>		
		</div>
	<h2>Logs</h2>
		<log-table content-type="content_type" object-id="selected_lab.id"></log-table>
	</div>
</div>
{% endblock %}

gcportal/templates/portal/policy.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load markdown_tags %}
{% block content %}
<form method="POST" action=".{% if next %}?next={{next}}{% endif %}">
 <h2>{{policy.title}}</h2>
 <p>{{policy.text|markup}}</p>
 {% csrf_token %}
 {{form|crispy}}
 {% if next %}<input type="hidden" name="next" value="{{next}}"/>{% endif %}
<button class="btn btn-primary">Submit</button>
</form>
{% endblock %}